# Generated by Django 4.0.4 on 2022-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(max_length=60),
        ),
    ]
